-- require('nerdtree').setup()

-- NERDTree
-- vim.g.NERDTreeDirArrowExpandable = ''
-- vim.g.NERDTreeDirArrowCollapsible = ''
-- vim.g.NERDTreeShowLineNumbers = 1
-- vim.g.NERDTreeAutoDeleteBuffer = 1
-- vim.g.NERDTreeDirArrows = 1
-- vim.g.NERDTreeShowHidden = 1
-- vim.g.NERDTreeQuitOnOpen = 1
-- vim.g.NERDTreeMinimalUI = 0
-- vim.g.NERDTreeWinSize = 38
-- vim.g.NERDTreeGlyphReadOnly = "RO"
